import Head from "next/head";
import { Container } from "react-bootstrap";
import Navigation from "../components/navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Beneath the Surface</title>
        <meta name="description" content="Generated by create next app" />

        {/* favicon block - as per https://realfavicongenerator.net/ */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

        {/* react boostrap */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous"
        />
      </Head>

      <Container className="cover-hero"
        fluid
        style={{
          backgroundImage: "url(../cover-hero.jpg)",
          backgroundRepeat: "no-repeat"
        }}
      >
        <Navigation />

        {/* hero banner component? */}
      </Container>

      {/* book preview component? */}
      {/* about component? */}
      {/* order component? */}
      {/* footer */}
    </div>
  );
}
