import Head from "next/head";
import { Container, Image, Stack } from "react-bootstrap";
import Navigation from "../components/navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Beneath the Surface</title>
        <meta name="description" content="Generated by create next app" />

        {/* favicon block - as per https://realfavicongenerator.net/ */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

        {/* react boostrap */}
        {/* <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        /> */}
      </Head>

      <Container
        className="cover-hero"
        fluid
        style={{
          backgroundRepeat: "no-repeat",
        }}
      >
        <Navigation />

        {/* hero banner component? */}
        <Stack gap={1} direction="horizontal" className="col-md-5 mx-auto cover">
          <Image fluid src="/hero/front-cover-sm.jpg" alt="" />
          <Container className="text-primary">
            <h1 className="display-6">BENEATH THE SURFACE</h1>
            <div>30 ways to pray for Japan</div>
          </Container>
        </Stack>
        <Container className="background-overlay"></Container>
      </Container>

      <Container
        className="cover-temp"
        fluid
        style={{
          backgroundImage: "url(../hero/reading-hero.jpg)",
          backgroundRepeat: "no-repeat",
        }}
      >
        <div> book preview component </div>
        {/* book preview component? */}
      </Container>

      <Container
        className="cover-temp"
        fluid
        style={{
          backgroundImage: "url(../hero/about-hero.jpg)",
          backgroundRepeat: "no-repeat",
          backgroundSize: "contain",
        }}
      >
        <stack className="col-md-5 mx-auto">
          <Container className="top-spacer">
            <h1 className="text-center"> ABOUT </h1>
            <Container style={{maxWidth: "670px"}}>
              <p>
                Japan is known for its natural beauty, distinctive culture, and advanced technology; there is much to
                admire. Visitors to Japan comment that people are considerate, streets are clean, trains are on time,
                food is presented beautifully. It is a land that leaves memorable first impressions. But beneath the
                surface, there is so much more–more to admire, but also much to wrestle with.
              </p>
              <p>
                Welcome to Beneath the Surface: 30 ways to pray for Japan. We invite you to move beyond first
                impressions to engage with the stories and concerns of Christians in Japan. Will you join us in praying
                for Japan?
              </p>
            </Container>
          </Container>
        </stack>
      </Container>

      <Container
        className="cover-temp"
        fluid
        style={{
          backgroundImage: "url(../hero/cover-hero.jpg)",
          backgroundRepeat: "no-repeat",
        }}
      >
        {/* order component? */}
      </Container>

      <Container
        style={{
          background: "#d5204a",
        }}
      >
        {/* footer */}
      </Container>
    </div>
  );
}
